// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace LibraryManagement.DataAccess.Migrations;

[DbContext(typeof(LibraryDbContext))]
[Migration("20260715150000_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Books",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                ISBN = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                Title = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                Author = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                Publisher = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                PublicationYear = table.Column<int>(type: "integer", nullable: true),
                Category = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                Shelf = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                AvailabilityStatus = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table => table.PrimaryKey("PK_Books", x => x.Id));

        migrationBuilder.CreateTable(
            name: "Users",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                Username = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                Email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: false),
                PasswordHash = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                FirstName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                LastName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                Role = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table => table.PrimaryKey("PK_Users", x => x.Id));

        migrationBuilder.CreateTable(
            name: "BorrowTransactions",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                UserId = table.Column<Guid>(type: "uuid", nullable: false),
                BookId = table.Column<Guid>(type: "uuid", nullable: false),
                BorrowDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                DueDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                ReturnDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                Status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BorrowTransactions", x => x.Id);
                table.ForeignKey(
                    name: "FK_BorrowTransactions_Books_BookId",
                    column: x => x.BookId,
                    principalTable: "Books",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "FK_BorrowTransactions_Users_UserId",
                    column: x => x.UserId,
                    principalTable: "Users",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(name: "IX_Books_Author", table: "Books", column: "Author");
        migrationBuilder.CreateIndex(name: "IX_Books_ISBN", table: "Books", column: "ISBN", unique: true);
        migrationBuilder.CreateIndex(name: "IX_Books_Title", table: "Books", column: "Title");
        migrationBuilder.CreateIndex(
            name: "IX_BorrowTransactions_BookId_Status",
            table: "BorrowTransactions",
            columns: new[] { "BookId", "Status" });
        migrationBuilder.CreateIndex(
            name: "IX_BorrowTransactions_UserId_Status",
            table: "BorrowTransactions",
            columns: new[] { "UserId", "Status" });
        migrationBuilder.CreateIndex(name: "IX_Users_Email", table: "Users", column: "Email", unique: true);
        migrationBuilder.CreateIndex(name: "IX_Users_Username", table: "Users", column: "Username", unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "BorrowTransactions");
        migrationBuilder.DropTable(name: "Books");
        migrationBuilder.DropTable(name: "Users");
    }
}
