// <auto-generated />
using LibraryManagement.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace LibraryManagement.DataAccess.Migrations;

[DbContext(typeof(LibraryDbContext))]
partial class LibraryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("Users");
            entity.HasKey(value => value.Id);
            entity.Property(value => value.Id).HasColumnType("uuid");
            entity.Property(value => value.Username).HasMaxLength(100).IsRequired();
            entity.Property(value => value.Email).HasMaxLength(320).IsRequired();
            entity.Property(value => value.PasswordHash).HasMaxLength(255).IsRequired();
            entity.Property(value => value.FirstName).HasMaxLength(100).IsRequired();
            entity.Property(value => value.LastName).HasMaxLength(100).IsRequired();
            entity.Property(value => value.Role).HasConversion<string>().HasMaxLength(32).IsRequired();
            entity.Property(value => value.CreatedAt).HasColumnType("timestamp with time zone");
            entity.Property(value => value.UpdatedAt).HasColumnType("timestamp with time zone");
            entity.HasIndex(value => value.Username).IsUnique();
            entity.HasIndex(value => value.Email).IsUnique();
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.ToTable("Books");
            entity.HasKey(value => value.Id);
            entity.Property(value => value.Id).HasColumnType("uuid");
            entity.Property(value => value.Isbn).HasColumnName("ISBN").HasMaxLength(20).IsRequired();
            entity.Property(value => value.Title).HasMaxLength(300).IsRequired();
            entity.Property(value => value.Author).HasMaxLength(200).IsRequired();
            entity.Property(value => value.Publisher).HasMaxLength(200);
            entity.Property(value => value.PublicationYear);
            entity.Property(value => value.Category).HasMaxLength(100);
            entity.Property(value => value.Shelf).HasMaxLength(100).IsRequired();
            entity.Property(value => value.AvailabilityStatus).HasConversion<string>().HasMaxLength(32).IsRequired();
            entity.Property(value => value.CreatedAt).HasColumnType("timestamp with time zone");
            entity.Property(value => value.UpdatedAt).HasColumnType("timestamp with time zone");
            entity.HasIndex(value => value.Isbn).IsUnique();
            entity.HasIndex(value => value.Title);
            entity.HasIndex(value => value.Author);
        });

        modelBuilder.Entity<BorrowTransaction>(entity =>
        {
            entity.ToTable("BorrowTransactions");
            entity.HasKey(value => value.Id);
            entity.Property(value => value.Id).HasColumnType("uuid");
            entity.Property(value => value.UserId).HasColumnType("uuid");
            entity.Property(value => value.BookId).HasColumnType("uuid");
            entity.Property(value => value.BorrowDate).HasColumnType("timestamp with time zone");
            entity.Property(value => value.DueDate).HasColumnType("timestamp with time zone");
            entity.Property(value => value.ReturnDate).HasColumnType("timestamp with time zone");
            entity.Property(value => value.Status).HasConversion<string>().HasMaxLength(32).IsRequired();
            entity.HasIndex(value => new { value.UserId, value.Status });
            entity.HasIndex(value => new { value.BookId, value.Status });
            entity.HasOne(value => value.User).WithMany(value => value.BorrowTransactions)
                .HasForeignKey(value => value.UserId).OnDelete(DeleteBehavior.Restrict);
            entity.HasOne(value => value.Book).WithMany(value => value.BorrowTransactions)
                .HasForeignKey(value => value.BookId).OnDelete(DeleteBehavior.Restrict);
        });
    }
}
